quadlets/bluefin-cli/bluefin-cli-distrobox-quadlet.container, quadlets/wolfi-toolbox/wolfi-distrobox-quadlet.container, toolboxes/bluefin-cli/Containerfile.bluefin-cli, toolboxes/wolfi-toolbox/Containerfile.wolfi
TODO: Find a way to not have systemd managed containers be seen by toolbox/distrobox while still letting prompt work.
=> fix: Need distrobox label for prompt

toolboxes/wolfi-toolbox/packages.wolfi
Refs
https://github.com/ublue-os/toolboxes/commit/7cd04424d72bac1200d1d6721e97f86c28a3adc6
https://github.com/ublue-os/bluefin/pull/812
=> chore: libcap version pin no longer required.

.github/workflows/build-bluefin-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml, README.md, toolboxes/bluefin-cli/Containerfile.bluefin-cli, toolboxes/wolfi-toolbox/Containerfile.wolfi
This introduces a Wolfi development variant of both Bluefin CLI and Wolfi Toolbox images, built from the Wolfi SDK image. These variants use the 'testing' tag and include tools such as melange, apko, and wolfictl for Wolfi package and image development.
=> feat: Add Wolfi development variants of Bluefin CLI and Wolfi Toolbox

.github/workflows/build-bluefin-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml, toolboxes/bluefin-cli/Containerfile.bluefin-cli
Drop the testing tag, and rename the Wolfi SDK based images as dx images to reflect that they're utilized by Ublue developers
=> chore(wolfi): Create dx variants of Bluefin CLI and Wolfi Toolbox

toolboxes/bluefin-cli/Containerfile.bluefin-cli, toolboxes/bluefin-cli/packages.bluefin-cli
@castrojo noticed that when using a quadlet, if there is no internet at startup the container cannot run. This comments out all of the package checks which requires internet.
This removes the ability to add additional_packages into the Exec= line of `bluefin-cli.container` to have them installed at startup.
=> fix: Patch distrobox-init for no-internet

toolboxes/bluefin-cli/Containerfile.bluefin-cli, toolboxes/bluefin-cli/files/etc/bashrc
Retrieves and extracts ble.sh. Enables both atuin and ble.sh via the bashrc
Resolves: https://github.com/ublue-os/toolboxes/issues/27
=> feat(bluefin-cli): Enable atuin and ble.sh out of the box

quadlets/bluefin-cli/bluefin-dx-cli.container, toolboxes/bluefin-cli/files/etc/profile.d/00-bluefin-cli-brew-firstrun.sh, toolboxes/bluefin-cli/files/etc/profile.d/homebrew-env.sh, toolboxes/bluefin-cli/files/usr/share/fish/vendor_conf.d/brew.fish
fix: Brew Cellar stored by hostname
=> fix: fish homebrew completions weren't sourced

.github/workflows/build-wolfi-toolbox.yml
Had `:` where `=` should have been used
=> fix(ci): Correct the assignment of build arguments to Wolfi Toolbox

toolboxes/wolfi-toolbox/Containerfile.wolfi
This is used when building packages locally so that they can be more easily installed. While helpful for quickly installing built packages, this gets hardcoded to the GitHub workspace directory and half the time an explicit installation path ends up being used anyway
=> fix(wolfi): Remove local repository reference

toolboxes/wolfi-toolbox/packages.wolfi-dx
This package doesn't align with the SDK and borks curl. On closer analysis, the correct package is `libcurl-openssl4`
=> fix(wolfi-dx-toolbox): Swap libcurl4 with libcurl-openssl4

toolboxes/wolfi-toolbox/Containerfile.wolfi
Realized that unlike in Bluefin CLI, we aren't clearing out /tmp for Wolfi resulting in the contents of /tmp being stored in the image.
=> chore(wolfi): Clean out /tmp, reduce image size

toolboxes/wolfi-toolbox/packages.wolfi
Fix https://github.com/ublue-os/toolboxes/issues/77
=> fix: add missing distrobox package `man`

toolboxes/powershell-toolbox/Containerfile.powershell, toolboxes/powershell-toolbox/packages.powershell
Resolves #11 
Add a new toolbox for Microsoft related tooling.
- Add initial package list
- Add PowerShell
- Add dotnet core and .NET sdk (LTS)
- Add Azure Command-Line Interface (azure-cli)
- Disable telemetry
- [Install the Azure CLI on Linux](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script)
- [dotnet-install scripts reference](https://learn.microsoft.com/en-gb/dotnet/core/tools/dotnet-install-script)
- [.NET releases](https://github.com/dotnet/core/blob/main/releases.md)
I am aware the COPY command is wrong for the final release, but I am still testing things locally so I will adjust it after the PR review.
=> feat: create powershell toolbox

README.md, toolboxes/powershell-toolbox/Containerfile.powershell, toolboxes/powershell-toolbox/packages.powershell, toolboxes/powershell-toolbox/profile.ps1
Relates to #11 
Improve the UX experience of the new PowerShell toolbox.
- Extend package list with various CLI utils
- bat
- eza
- fd
- fzf
- gawk
- jq
- ripgrep
- sed
- zoxide
- Fix missing PowerShell modules issue by installing PowerShell as a .[NET Global tool](https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.4#install-as-a-net-global-tool)
- Add initial [PowerShell profile](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4) with the following features:
- [Oh My Posh](https://ohmyposh.dev/) integration with [mt](https://ohmyposh.dev/docs/themes#mt) theme 
- [Zoxide](https://github.com/ajeetdsouza/zoxide) integration
- [McFly](https://github.com/cantino/mcfly) …
=> feat: powershell toolbox improvements

.github/workflows/build-blincusui-app.yml, .github/workflows/build-bluefin-toolbox.yml, .github/workflows/build-fedora-toolbox.yml, .github/workflows/build-incus-app.yml, .github/workflows/build-powershell.yml, .github/workflows/build-ubuntu-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml
Do not merge yet! https://www.redhat.com/sysadmin/faster-container-image-pulls
Met with the podman team on this and got the demo. Note that all the stuff required for bootc and rpm-ostree are in flight and inprogress. However this has been in podman and docker for a while now, so the toolboxes are a perfect place to get some savings.
I built this in castrojo/bluefin-cli. Needs to be on an ubuntu-24.04 builder so that the newer version of podman is on there. Then we add `--compression-format=zstd:chunked` to the podman push step. Podman and docker will know it's zstd:chunked and just do the right thing. 
podman pull ghcr.io/castrojo/bluefin-cli
And make note of the output. Leaving this as draft so we can observe what a few days of updates looks like in practice.
=> chore: push images with zstd:chunked

.github/workflows/build-blincusui-app.yml, .github/workflows/build-bluefin-toolbox.yml, .github/workflows/build-fedora-toolbox.yml, .github/workflows/build-incus-app.yml, .github/workflows/build-powershell.yml, .github/workflows/build-ubuntu-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml
Reverts ublue-os/toolboxes#101
We can't swap until ubuntu-24.04 runners are out of beta in GitHub, otherwise builds downstream will break. https://universal-blue.discourse.group/t/the-bluefin-cli-container/704/16
=> revert: "chore: push images with zstd:chunked"

toolboxes/bluefin-cli/packages.bluefin-cli
Reverts merge commit fc8013a due to uutils cp breaking brew install.
Closes: https://github.com/ublue-os/toolboxes/issues/111
=> fix(bluefin-cli): Revert "Merge pull request #53 from ublue-os/uutils"

toolboxes/bluefin-cli/files/etc/profile.d/modern-unix.sh
Fixes #67
This adds an alias for cat to use bat without line numbers or paging so
we get the same behaviour as cat with the syntax highlighting from bat.
=> feat(bluefin-cli): Add alias for cat

toolboxes/debian-toolbox/Containerfile.debian
idk when or how I committed the wrong file here
=> fix: Actually build debian toolbox from debian

.github/workflows/build-blincusui-app.yml, .github/workflows/build-debian-toolbox.yml, .github/workflows/build-incus-app.yml, .github/workflows/build-ubuntu-toolbox.yml, .github/workflows/build-wolfi-toolbox.yml
In some github workflows, the param
```          
extra-args: |
--compression-format=zstd:chunked
```
is used with the `docker/login-action` instead with `redhat-actions/push-to-registry`. This raises a warning during build, thou build completes successfully.
=> fix(build): Move misplaced 'extra-args' param.

toolboxes/wolfi-toolbox/Containerfile.wolfi
The following [commit](https://github.com/wolfi-dev/os/commit/8534cbcb94b665654df9af10295baf8716b532b2) broke Wolfi builds.
```
STEP 9/12: RUN mkdir -p /usr/local/bin  &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree
error running container: from /usr/bin/crun creating container for [/bin/sh -c mkdir -p /usr/local/bin  &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak &&     ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman &&     ln -fs /usr/bin/distrobox-host-exec …
```
=> fix(wolfi): remove /bin/sh symlink

quadlets/fedora-toolbox/fedora-toolbox-quadlet.container, quadlets/ubuntu-toolbox/ubuntu-toolbox-quadlet.container
- Home paths now match the other quadlet files. This fixes `/var/var` mount errors.
- Set Podman dns to none as toolbox-init-container(1) handles /etc/resolv.conf sync.[^1]
[^1]: #128
=> fix(toolbox-quadlets): Correct home and dns

.github/workflows/build-arch-toolbox.yml, README.md, quadlets/arch-toolbox/arch-distrobox-amdgpupro-quadlet.container, quadlets/arch-toolbox/arch-distrobox-quadlet.container, quadlets/arch-toolbox/arch-toolbox-amdgpupro-quadlet.container, quadlets/arch-toolbox/arch-toolbox-quadlet.container, systemd/arch-toolbox/arch-distrobox-amdgpupro-oneshot.service, systemd/arch-toolbox/arch-distrobox-amdgpupro.ini, systemd/arch-toolbox/arch-distrobox-oneshot.service, systemd/arch-toolbox/arch-distrobox.ini, toolboxes/arch-toolbox/Containerfile.arch, toolboxes/arch-toolbox/Containerfile.archamdgpupro
moves https://github.com/ublue-os/arch-distrobox  as per #1 
- ubuntu 24.04 runner, zstd:chunked
- added quadlet files, systemd services and distrobox .ini files
- split the containerfile into 2 files for with and without amdgpupro
I mostly copy and pasted the original workflow and it may still need some work if it is not up to standards or could be simpler. This is my first time playing around with gh actions. So I will probably still need some help with that
=> chore(arch): move to centralized repo

.github/renovate.json5
Tells Renovate to group the debian update in with the other images.
Also configures auto merging.
=> chore(renovate): fix debian automerge/group rule

toolboxes/ubuntu-toolbox/packages.ubuntu
Would be nice to have that available by default.
I didn't add the `find` alias [found in bluefin-cli](https://github.com/ublue-os/toolboxes/blob/main/toolboxes/bluefin-cli/files/etc/profile.d/modern-unix.sh#L19-L20) since that seems too encroaching.
=> feat(ubuntu): add fd

.github/renovate.json5
Now Renovate runs as a GitHub Action, it doesn't seem to keep track of when it was previously ran.
To fix this, we can force the specific times where Renovate is allowed to create PRs.
Renovate doesn't care about minute granularity, so use a wildcard.
=> chore(renovate): hardcode schedule with specific times
